spring:
  application:
    name: pay-platform
  profiles:
    active: dev
  datasource:
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/pay?useUnicode=true&characterEncoding=utf8
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
server:
  port: 8080

redis:
  host: localhost
  port: 6379
  password:
  # 连接超时时间（毫秒）
  timeout: 10000
  jedis:
    pool:
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 100
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

alipay:
  url: https://openapi.alipay.com/gateway.do
  app_id: 2019082666449529
  format: JSON
  charset: utf-8
  sign_type: RSA2
  version: 1.0
  private_key:
  public_key:

wechat-pay:
  appid: wx0cd209a91f1fa256
  mch_id: 1520874231
  cert_path:
  app_secret: b90d45be9c6e55f4b1383ba193ac2427
  sign_type: MD5



